Create Post Screen Added
doubtless46/doubtless-app pull request #3
Opened 2023-05-01 13:14 UTC by Aditya13s

2023-05-01 15:42 UTC, tusharojha commented
@Aditya13s Please attach a screenshot of the app.

2023-05-02 06:20 UTC, sidsharma2002 requested changes

2023-05-02 12:53 UTC, Aditya13s commented on app/src/main/java/com/doubtless/doubtless/screens/post/CreatePostFragment.kt
> +            "Time" to Date(),
Yes Date().toString can be converted back to Date object using Date.parse(string)

2023-05-02 15:14 UTC, Aditya13s commented on app/src/main/res/layout/fragment_view_post.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Replaced Frame Layout with Constraint Layout

2023-05-07 14:21 UTC, Aditya13s commented
Not Needed

2023-05-07 14:21 UTC, closed without merging