Home Screen Filter Tags
doubtless46/doubtless-app pull request #77
Opened 2023-06-28 08:33 UTC by Aditya13s

2023-06-28 13:45 UTC, sidsharma2002 requested changes

2023-06-28 13:45 UTC, sidsharma2002 commented on app/src/main/java/com/doubtless/doubtless/screens/doubt/HomeMainScreenFragment.kt
> +        viewModel.fetchTags()
if there is already data fetched then dont fetch again, if (viewmodel.result.data != null) something like this

2023-06-28 14:27 UTC, Aditya13s commented
@sidsharma2002 check the changes

2023-06-28 15:43 UTC, sidsharma2002 commented
@Aditya13s add analytics

2023-06-29 08:51 UTC, Aditya13s commented
@sidsharma2002 please check the pull request

2023-06-29 09:03 UTC, merged